version: "3.8"

services:
  # db
  db:
    build:
      context: ./db
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
  
  # wordpress
  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress
  #   ports:
  #     - 8080:80
  #   restart: always
  #   volumes:
  #     - ./app/wp-content:/var/www/html/wp-content
  #     - ./app/wp-admin:/var/www/html/wp-admin
  #     - ./app/wp-includes:/var/www/html/wp-includes
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}